2023-09-15 22:18:03,127   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-15 22:18:06,546   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
2023-09-15 22:18:06,551   -   test_330_switch_tab   -   ERROR   -   Assertion Error Searches 1146 (42S02): Table 'dariya_logs.reporter_logs' doesn't exist
2023-09-15 22:24:13,376   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-15 22:24:15,330   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
2023-09-15 22:24:15,333   -   test_330_switch_tab   -   ERROR   -   Assertion Error Searches 1146 (42S02): Table 'dariya_logs.reporter_logs' doesn't exist
2023-09-15 22:34:46,398   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-15 22:34:48,728   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
2023-09-15 22:34:48,827   -   test_330_switch_tab   -   ERROR   -   Assertion Error Searches 1406 (22001): Data too long for column 'logs' at row 1
2023-09-15 22:39:10,314   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-15 22:39:12,269   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
2023-09-16 22:01:21,299   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,327   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,335   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,345   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,354   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,364   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,372   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:01:21,380   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,457   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,486   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,496   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,503   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,512   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,521   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,530   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:04:16,539   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,624   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,652   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,662   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,671   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,681   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,689   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,698   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:38,708   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,486   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,514   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,523   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,532   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,540   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,547   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,556   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:06:55,564   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,348   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,378   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,387   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,395   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,405   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,418   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,426   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:09:11,436   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,302   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,330   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,340   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,349   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,358   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,369   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,377   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:10:26,389   -   setup_class   -   WARNING   -   Error connecting to:[Errno 2] No such file or directory: 'device_data/data_device.yml'
2023-09-16 22:16:31,104   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ef8126b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,225   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3eda01480>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,315   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3eda59180>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,417   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ee3efaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,510   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ee792f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,613   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ee3ceaa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,704   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ee3079a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:16:31,809   -   setup_class   -   WARNING   -   Error connecting to:HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ed9478b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-09-16 22:20:30,745   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSwitchTab' has no attribute 'read_data_device'
2023-09-16 22:20:30,776   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:20:30,786   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestCrossButtonSearchBox' has no attribute 'read_data_device'
2023-09-16 22:20:30,796   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:20:30,806   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:20:30,817   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:20:30,828   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:20:30,838   -   setup_class   -   WARNING   -   Error connecting to:type object 'TestSearch' has no attribute 'read_data_device'
2023-09-16 22:21:20,108   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-16 22:21:22,214   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
2023-09-16 22:21:22,215   -   test_330_switch_tab   -   ERROR   -   Assertion Error Searches [Errno 2] No such file or directory: 'logs_config/logs.log'
2023-09-16 22:22:00,336   -   test_330_switch_tab   -   INFO   -   Switch tab test is running
2023-09-16 22:22:02,624   -   test_330_switch_tab   -   INFO   -   Switch tab test is successful
